version: "3.2"

services:
    gitlab-runer:
        image: gitlab/gitlab-runner
        volumes:
            - "/data/gitlab/gitlab-runner:/etc/gitlab-runner"
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "/etc/hosts:/etc/hosts"
            - "/root/project:/root/project"
        network_mode: "host"
