version: "3.2"

services:
    gitlab_serve:
        image: gitlab/gitlab-ce
        hostname: gitlab.zhanghanlin.com
        ports: 
            - "8089:80"
        volumes:
            - "/data/gitlab/config:/etc/gitlab"
            - "/data/gitlab/logs:/var/log/gitlab"
            - "/data/gitlab/data:/var/opt/gitlab"
