version: "3.7"
services: 

    mongodb:
        image: mongo:latest
        container_name: mango
        ports: 
            - "27017:27017"
        volumes:
            - mango_data:/data/db
            - "./initmongo:/docker-entrypoint-initdb.d/"
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=zhanghanlin
            - MONGO_INITDB_ROOT_PASSWORD=13956668172
        command: --dbpath /data/db  --auth
        restart: always
        
volumes:
    mango_data:

        