version: "3.7"
services: 

    redis:
        image: redis:latest
        container_name: redis
        command: redis-server --requirepass 123456
        ports: 
            - "6379:6379"
        restart: always
