version: "3.7"
services: 

    redis:
        image: redis:latest
        container_name: redis
        ports: 
            - "6379:6379"
        environment:
            - requirepass="123456"
        restart: always
