version: "3.7"
services: 

    gitlab:
        image: 'gitlab/gitlab-ce:latest'
        restart: always
        hostname: 'gitlab.example.com'
        environment:
            GITLAB_OMNIBUS_CONFIG: |
                external_url 'http://gitlab.example.com'
        ports:
            - "80:80"
            - "443:443"
            - "22:22"
        volumes:
            - gitlab_config:/etc/gitlab
            - gitlab_logs:/var/log/gitlab
            - gitlab_data:/var/opt/gitlab
volumes:
    gitlab_config:
    gitlab_logs:
    gitlab_data: