version: "3.7"
services: 

    mongodb:
        image: mongo:latest
        container_name: mango
        ports: 
            - "27017:27017"
        volumes:
            - mango_data:/data/db
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=123456
        command: --dbpath /data/db  --auth
        restart: always
        
volumes:
    mango_data:

        